## Numpy Random Module

- rand           : Random value is given
- randn          : Return a sample (or samples) from the "Standard Normal" Distribution
- randint        : Return random integers from low (inclusive) to high (exclusive)
- random         : Return random floats in the half-open interval[0.0,1.0]
- choice         : Generates a random sample from a given 1-D array
- Shuffle        : Shuffles the contents of a sequence

In [2]:
import numpy as np 

In [4]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [95]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [7]:
### use "import np.random as random" or just use "np.random"

In [96]:
np.random.shuffle(a)
print(a)


[ 8 13 11  5  7 14  9 10 12  6]


In [10]:
a = np.random.rand(2,3)
print(a)

[[0.16301009 0.03502977 0.49473909]
 [0.67650862 0.72263841 0.80049153]]


In [12]:
# Returns values from Standard Normal Distribution
a = np.random.randn(2,3)
print(a)

[[-1.90738023  0.03730257  0.26628668]
 [-1.20943166  0.95289884  0.94271348]]


In [99]:
a = np.random.randint(5,10,3)
print(a)

#Randomly pick one element from an array

element = np.random.choice([1,4,3,2,11,27])
print(element)

[9 6 7]
11


In [108]:
# To store the state of the random numbers
np.random.seed(1)
np.random.shuffle(a)
print(a)


[9 7 6]
