### Some more Numpy Functions - Statistics
- min, max
- mean
- median
- average
- variance
- standard deviation

In [3]:
import numpy as np

In [6]:
a = np.array([[1,2,3,4], [7,6,2,0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [11]:
print(np.min(a))
#in case of a multi-dimentional array
print(np.min(a, axis=0)) # minimum along x-axis
print(np.min(a, axis=1)) # minimum along y-axis

0
[1 2 2 0]
[1 0]


In [13]:
# Mean - average of all the elements

b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))

print(np.mean(a,axis = 0))
print(np.mean(a,axis = 1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [14]:
c = np.array([1,5 ,4,2,0])
print(np.median(c))

2.0


In [15]:
# Mean Vs Average

# Mean is just the basic average (sum divided by N)
print(np.mean(c))

# Average is weighted (sum(elements*their weights) divided by N)

w = np.array([1,2,3,4,5]) #weights
print(np.average(c, weights = w))



2.4
2.066666666666667


In [17]:
print(np.mean(c))
w = np.array([1,1,1,1,1])
print(np.average(c, weights = w))
# if weight is 1, mean = average


2.4
2.4


In [18]:
# Standard Deviation

#sigma = sqrt [(1/N)*sum(x of i - mu)**2 for i in range(1,N+1)]

# if we dont want to use the in-built function, then:

u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

1.854723699099141


In [20]:
# if we use the in-built  function, we get:

dev = np.std(c)
print(dev)

1.854723699099141


In [21]:
# Variance (square of standard deviation)

print(myStd**2)

3.440000000000001


In [22]:
# in-built function for variance
print(np.var(c))

3.4400000000000004
