### Linear Algebra

 In this tutorial, we will cove rsome basics of Linear Algebra as seen in DEEP LEARNING BOOK, with a focus on using numpy.
 
 #### 1. Scalers and Vectors
- <b>Scaler</b> is a single number, denoted as x.
- <b>Vector</b> is an array of scalers, denoted by <b>x</b>.
    - Thus, a vector has n scalers, x1, x2, ....., xn
    - Note that indexing here begins with 1, unlike python (where it begins with 0)
  

#### Scalers
- x = 5
- y = 5.5

#### Vectors (generally means column vector)
- x = [3 1 5]

### We will represent a vector as a column vector.
### that is having multiple rows


In [3]:
import numpy as np

In [13]:
#output in the form of a row
x1 = np.array([4,5,6])
print(x1)
print(x1.shape)


[4 5 6]
(3,)


In [20]:
#output in the form of a column
x = np.array([[4], [5], [8], [9]])
print(x)
print(x.shape)

[[4]
 [5]
 [8]
 [9]]
(4, 1)


In [21]:
# The difference - the change in how we access the elements
print(x1[0])
print(x[0])
print(x[0][0])

4
[4]
4


In [22]:
x = x.reshape((-1,))
print(x)

[4 5 8 9]


In [24]:
# Reshape Operation
x = x.reshape((-1,2))
print(x)

[[4 5]
 [8 9]]


#### 2. Matrices and Tensors
- <b>Matrix</b> is a 2D array of scalars, denoted by <b><i>X</i></b>
    - A matrix has m rows and n columns
    - Indexing starts with 0
    - Each individual element, such as X(1,1), is a scalar.
    - If m = n, the matrix is known as Square Matrix.
- <b>Tensor</b> is an array with more than 2 axes, denoted as <b>X</b>
    - Think of Tensor as a generalization of an array with more than 2 axes.


In [29]:
# Here is a Matrix
X = np.array([[4,5,7], [10,11,13], [56,80,90]])
print(X.shape)
print(X)

(3, 3)
[[ 4  5  7]
 [10 11 13]
 [56 80 90]]


In [28]:
print(X[1][1])

11


In [31]:
X[1:, :] = 2  # [s:e+1]
print(X)

[[4 5 7]
 [2 2 2]
 [2 2 2]]


In [33]:
# Here is a Tensor
T = np.array([[[4,5,7], [10,11,13]], [[56,80,90], [9,8,10]]])
print(T)
print(T.shape)
# helpful in neural models, deep learning

[[[ 4  5  7]
  [10 11 13]]

 [[56 80 90]
  [ 9  8 10]]]
(2, 2, 3)


### 3. Transpose
For a 2D matrix, transpose can be obtained as follows:
(A^T)(i,j) = A(j,i)
For a vector, transpose makes the column vector into a row. Thus a column vector can also be represented as x = [x1,x2,x3]^T

In [37]:
print(x)
xt = np.transpose(x)
print(xt)

[[4 5]
 [8 9]]
[[4 8]
 [5 9]]


In [40]:
y = x.reshape(-1,1)
print(y)
print(np.transpose(y))
print(np.transpose(y).shape)

[[4]
 [5]
 [8]
 [9]]
[[4 5 8 9]]
(1, 4)


### 4. Broadcasting
- You can add a scalar to a vector, and numpy will add it to each element in a vector

    x + a = xi + a


- Similarly, you can add a vector to a matrix, and numpy will add the vector to each column of the matrix

In [27]:
# Any mathematical operation directly on list throws an error

l = [1,2,3,4]

# Operation 1
l = l + 1

# Operation 2
l = l **2

print(l)

TypeError: can only concatenate list (not "int") to list

In [30]:
# Numpy allows you to perform math operations directly on a list
l = [1,2,3,4]
l = np.array(l)
l = l + 1
print(l)

[2 3 4 5]


In [31]:
l = [1,2,3,4]
l = np.array(l)
l = l**2
print(l)

[ 1  4  9 16]


In [36]:
# For a matrix,

l = [[1,2,3,4], [5,6,7,8]]
l = np.array(l)
l = l**2
l+=1
print(l)
print(l+1)

[[ 2  5 10 17]
 [26 37 50 65]]
[[ 3  6 11 18]
 [27 38 51 66]]


In [38]:
np.sqrt(l)# , dtype='float64')

array([[1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.09901951, 6.08276253, 7.07106781, 8.06225775]])

### 5. Matrix Multiplication
This is perhaps one operation that you would use quite frequently in any ML/DL model. You should remember a few things about multiplication.

- C = AB is only defined when the second dimension of A matches the first dimension of B.
- Further, if A is of shape(m,n), and B of shape(n,p), then C is of shape (m,p).
- This operation is concretely defined as C(i,j) = sum(A(i,k)*B(k,j))
    - C(i,j) is computed by taking the dot produt of i-th row of A, with j-th column of B.
- A more useful method to think matrix multiplication is as:
    linear combination of columns of A wighted by column entries of B.

In [4]:
X = np.array([[4,5,7], [10,11,13], [56,80,90]])
Y = np.array([[40,50,70], [100,110,130], [560,800,900]])

In [5]:
print(X.shape)
print(Y.shape)

(3, 3)
(3, 3)


In [6]:
print(X)
print(Y)

[[ 4  5  7]
 [10 11 13]
 [56 80 90]]
[[ 40  50  70]
 [100 110 130]
 [560 800 900]]


In [7]:
prod = np.dot(X,Y)
print(prod)

[[ 4580  6350  7230]
 [ 8780 12110 13830]
 [60640 83600 95320]]


### 6. Element Wise Multiplication : Hadamard Product

Element wise multiplication A.B
Notice how numpy uses the * for this. Important to be careful, and not  to confuse this with matrix multiplication.

In [11]:
# Different from Element wise multiplication
X = np.array([[4,5,7], [10,11,13], [56,80,90]])

Y = np.eye(3)

print(X)

Y = Y *2
Y = Y + 1
print(Y)

[[ 4  5  7]
 [10 11 13]
 [56 80 90]]
[[3. 1. 1.]
 [1. 3. 1.]
 [1. 1. 3.]]


In [12]:
print(X*Y)

[[ 12.   5.   7.]
 [ 10.  33.  13.]
 [ 56.  80. 270.]]


### 7. Norms
- Norm can be thought of as a proxy for size of a vector.

We define L^p norm ||X||p = (Sum|xi|^p)^1/p

p >= 1, p belongs R
- Norm is a function that maps vectors to non-negative values. A norm satisfies the following properties:
    - f(x) = 0 => x = 0
    - f(x+y) <= f(x) + f(y) (Triangle Inequality)
    - For all a belonging to R, f(a.x) = |a|f(x)
    
- 

In [21]:
x = np.array([-5,3,10])

In [22]:
lp2 = np.linalg.norm(x)
print(lp2)

11.575836902790225


In [23]:
lp1 = np.linalg.norm(x,ord=1)
print(lp1)

18.0


In [25]:
lpinf = np.linalg.norm(x,ord = np.inf)
print(lpinf)

10.0


In [39]:
################# QUIZ ###############################

In [46]:
# Question 1
# (a.)
r = np.array([[2,-2,1],[-1,2,-1],[2,-4,1]])
lpinf = np.linalg.norm(r,ord = np.inf)
print(lpinf)

7.0


In [47]:
# (b.)
r = np.array([[2,-2,1],[-1,2,-1],[2,-4,1]])
lp2 = np.linalg.norm(r)
print(lp2)

6.0


In [51]:
# Question 2
A = np.array([[1,-3,4],[-2,10,-7],[0,1,0], [0,0,0]])
B = np.array([[5,0],[-2,11],[-3,12]])
#print(A)
#print(B)

prod = np.dot(A,B)
print(prod)

[[-1 15]
 [-9 26]
 [-2 11]
 [ 0  0]]
