### Pandas
- DataFrame - Special Object to data in tabular form (Rows & Columns)

In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import pandas as pd
import numpy as np

In [6]:
# Try to create a data frame
user_data = {
    "MarksA": np.random.randint(1,100,5),
    "MarksB": np.random.randint(1,100,5),
    "MarksC": np.random.randint(1,100,5)
    
}

In [8]:
user_data

{'MarksA': array([89, 40, 67, 41, 81]),
 'MarksB': array([61, 63, 27, 23, 63]),
 'MarksC': array([39, 29, 22, 99, 99])}

In [16]:
df = pd.DataFrame(user_data, dtype = 'float32')
print(df)

   MarksA  MarksB  MarksC
0    89.0    61.0    39.0
1    40.0    63.0    29.0
2    67.0    27.0    22.0
3    41.0    23.0    99.0
4    81.0    63.0    99.0


In [11]:
df.head()

MarksA  MarksB  MarksC
0      89      61      39
1      40      63      29
2      67      27      22
3      41      23      99
4      81      63      99

In [12]:
df.head(n=3)

MarksA  MarksB  MarksC
0      89      61      39
1      40      63      29
2      67      27      22

In [14]:
print(df.columns)

Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')


In [18]:
df.to_csv('marks.csv')

In [23]:
my_data = pd.read_csv('marks.csv')
my_data = my_data.drop(columns=['Unnamed: 0'])
my_data

MarksA  MarksB  MarksC
0    89.0    61.0    39.0
1    40.0    63.0    29.0
2    67.0    27.0    22.0
3    41.0    23.0    99.0
4    81.0    63.0    99.0

## Pandas Basics - 2 

In [24]:
my_data.describe()

MarksA    MarksB     MarksC
count   5.000000   5.00000   5.000000
mean   63.600000  47.40000  57.600000
std    22.512219  20.51341  38.272706
min    40.000000  23.00000  22.000000
25%    41.000000  27.00000  29.000000
50%    67.000000  61.00000  39.000000
75%    81.000000  63.00000  99.000000
max    89.000000  63.00000  99.000000

In [25]:
my_data.head()

MarksA  MarksB  MarksC
0    89.0    61.0    39.0
1    40.0    63.0    29.0
2    67.0    27.0    22.0
3    41.0    23.0    99.0
4    81.0    63.0    99.0

In [26]:
my_data.tail()

MarksA  MarksB  MarksC
0    89.0    61.0    39.0
1    40.0    63.0    29.0
2    67.0    27.0    22.0
3    41.0    23.0    99.0
4    81.0    63.0    99.0

In [27]:
my_data.tail(n=3)

MarksA  MarksB  MarksC
2    67.0    27.0    22.0
3    41.0    23.0    99.0
4    81.0    63.0    99.0

In [28]:
# to access a particular row

df.iloc[3]

MarksA    41.0
MarksB    23.0
MarksC    99.0
Name: 3, dtype: float32

In [29]:
# to access a particular value (inside a row and a column)

df.iloc[3][1]

23.0

In [30]:
df.iloc[3,1]

23.0

In [40]:
# to find the index of a column using the name of the column
idx = [df.columns.get_loc('MarksB'),df.columns.get_loc('MarksC')]
print(idx)

[1, 2]


In [41]:
df.iloc[3,idx]

MarksB    23.0
MarksC    99.0
Name: 3, dtype: float32

In [42]:
df.iloc[:3, idx]

MarksB  MarksC
0    61.0    39.0
1    63.0    29.0
2    27.0    22.0

In [43]:
#same result
df.iloc[:3, [1,2]]

MarksB  MarksC
0    61.0    39.0
1    63.0    29.0
2    27.0    22.0

In [44]:
## Sort your dataframe
my_data

MarksA  MarksB  MarksC
0    89.0    61.0    39.0
1    40.0    63.0    29.0
2    67.0    27.0    22.0
3    41.0    23.0    99.0
4    81.0    63.0    99.0

In [46]:
my_data.sort_values(by=['MarksA'], ascending=False)

MarksA  MarksB  MarksC
0    89.0    61.0    39.0
4    81.0    63.0    99.0
2    67.0    27.0    22.0
3    41.0    23.0    99.0
1    40.0    63.0    29.0

In [47]:
my_data.sort_values(by=['MarksA'], ascending=True)

MarksA  MarksB  MarksC
1    40.0    63.0    29.0
3    41.0    23.0    99.0
2    67.0    27.0    22.0
4    81.0    63.0    99.0
0    89.0    61.0    39.0

In [ ]:
my_data.sort_values(by=['MarksA'], ascending=True)

In [49]:
my_data.sort_values(by=['MarksC','MarksA'], ascending=False)

MarksA  MarksB  MarksC
4    81.0    63.0    99.0
3    41.0    23.0    99.0
0    89.0    61.0    39.0
1    40.0    63.0    29.0
2    67.0    27.0    22.0

In [50]:
data_array = my_data.values

In [51]:
print(type(my_data))
print(my_data.shape)

<class 'pandas.core.frame.DataFrame'>
(5, 3)


In [52]:
print(data_array)

[[89. 61. 39.]
 [40. 63. 29.]
 [67. 27. 22.]
 [41. 23. 99.]
 [81. 63. 99.]]


In [53]:
print(type(data_array))

<class 'numpy.ndarray'>


In [54]:
data_array.shape

(5, 3)

In [55]:
data_array[2,2]

22.0

In [ ]:
# Numpy array back into dataframe

In [56]:
new_df = pd.DataFrame(data_array, dtype = 'int32', columns = ['Physics', 'Chemistry', 'Maths'])

In [57]:
new_df

Physics  Chemistry  Maths
0       89         61     39
1       40         63     29
2       67         27     22
3       41         23     99
4       81         63     99

In [59]:
new_df.to_csv("PCM.csv",index=False)

In [60]:
pcm = pd.read_csv('PCM.csv')

In [61]:
print(pcm)

   Physics  Chemistry  Maths
0       89         61     39
1       40         63     29
2       67         27     22
3       41         23     99
4       81         63     99


### Load and Visualize MNIST Dataset Using Pandas and Matplotlib

In [63]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv()